[package]
name = "little_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
lazy_static = "1.5.0"
sequential-test = "0.2.4"
serde = { version = "1.0.209", features = ["derive"] }
